name: Mobile Preview Builds

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: EAS build profile
        default: preview
        options:
          - preview
          - production

jobs:
  android-build:
    type: build
    params:
      platform: android
      profile: ${{ inputs.profile }}

  ios-build:
    type: build
    params:
      platform: ios
      profile: ${{ inputs.profile }}
