ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_quiet_hours_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_quiet_from TEXT NOT NULL DEFAULT '22:00';
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_quiet_to TEXT NOT NULL DEFAULT '08:00';
