export type DocumentType = "CONTRACT" | "INVOICE" | "ACT" | "RECONCILIATION"

/**
 * Список placeholder'ов для каждого типа документа — для отображения
 * пользователю при загрузке шаблона ("какие поля доступны").
 */
export const PLACEHOLDER_DOCS: Record<DocumentType, { key: string; label: string }[]> = {
  CONTRACT: [
    { key: "contract_number", label: "Номер договора" },
    { key: "contract_date", label: "Дата договора" },
    { key: "contract_date_long", label: "Дата договора прописью" },
    { key: "tenant_name", label: "Название арендатора" },
    { key: "tenant_legal_type", label: "Правовая форма арендатора" },
    { key: "tenant_bin", label: "БИН/ИИН арендатора" },
    { key: "tenant_iin", label: "ИИН арендатора" },
    { key: "tenant_address", label: "Адрес арендатора" },
    { key: "tenant_actual_address", label: "Фактический адрес арендатора" },
    { key: "tenant_phone", label: "Телефон арендатора" },
    { key: "tenant_email", label: "Email арендатора" },
    { key: "tenant_bank", label: "Банк арендатора" },
    { key: "tenant_iik", label: "ИИК арендатора" },
    { key: "tenant_bik", label: "БИК арендатора" },
    { key: "tenant_director", label: "Директор арендатора" },
    { key: "tenant_director_short", label: "Директор арендатора кратко" },
    { key: "tenant_position", label: "Должность подписанта арендатора" },
    { key: "tenant_basis", label: "Основание действия арендатора: Уведомление/Устав/лицензия" },
    { key: "tenant_basis_document", label: "Документ-основание арендатора" },
    { key: "landlord_name", label: "Название арендодателя" },
    { key: "landlord_short", label: "Краткое название арендодателя" },
    { key: "landlord_bin", label: "БИН арендодателя" },
    { key: "landlord_iin", label: "ИИН арендодателя" },
    { key: "landlord_address", label: "Адрес арендодателя" },
    { key: "landlord_iik", label: "ИИК арендодателя" },
    { key: "landlord_bik", label: "БИК арендодателя" },
    { key: "landlord_bank", label: "Банк арендодателя" },
    { key: "landlord_second_iik", label: "Второй ИИК арендодателя" },
    { key: "landlord_second_bik", label: "Второй БИК арендодателя" },
    { key: "landlord_second_bank", label: "Второй банк арендодателя" },
    { key: "landlord_director", label: "Директор арендодателя" },
    { key: "landlord_basis", label: "Основание действия арендодателя" },
    { key: "building_name", label: "Название объекта" },
    { key: "building_address", label: "Адрес объекта" },
    { key: "placement", label: "Расположение помещения/этажа" },
    { key: "space_number", label: "Номер помещения" },
    { key: "floor_name", label: "Этаж" },
    { key: "space_area", label: "Площадь, м²" },
    { key: "area", label: "Площадь числом" },
    { key: "area_num", label: "Площадь числом" },
    { key: "area_str", label: "Площадь с единицей м²" },
    { key: "monthly_rent", label: "Арендная плата, ₸/мес" },
    { key: "monthly_rent_num", label: "Арендная плата числом" },
    { key: "monthly_rent_with_words", label: "Сумма цифрами и прописью" },
    { key: "monthly_rent_words", label: "Сумма аренды прописью" },
    { key: "rent_in_words", label: "Сумма прописью" },
    { key: "rate_per_sqm", label: "Ставка за м²" },
    { key: "rate_per_sqm_num", label: "Ставка за м² числом" },
    { key: "rent_clause", label: "Пункт 3.1 с правильным расчетом аренды" },
    { key: "rent_terms_clause", label: "Пункт аренды с режимом расчета" },
    { key: "rent_basis", label: "Основание расчета аренды" },
    { key: "start_date", label: "Дата начала" },
    { key: "start_date_long", label: "Дата начала прописью" },
    { key: "contract_start", label: "Дата начала договора" },
    { key: "end_date", label: "Дата окончания" },
    { key: "end_date_long", label: "Дата окончания прописью" },
    { key: "contract_end", label: "Дата окончания договора" },
    { key: "payment_due_day", label: "Срок оплаты (число)" },
    { key: "penalty_percent", label: "Размер пени, %/день" },
    { key: "prolongation_clause", label: "Пункт 2.2 без автоматической пролонгации" },
    { key: "contract_prolongation_clause", label: "Пункт продления договора" },
    { key: "esf_clause", label: "Пункт про ЭСФ/счет-фактуру" },
    { key: "invoice_clause", label: "Пункт про счет на оплату и ЭСФ" },
    { key: "additional_services_clause", label: "Пункт про дополнительные услуги" },
    { key: "utilities_clause", label: "Пункт про отопление, свет, воду и доп. услуги" },
    { key: "signage_clause", label: "Пункт про видеокамеру/вывеску по согласованию сторон" },
  ],
  INVOICE: [
    { key: "invoice_number", label: "Номер счёта" },
    { key: "invoice_date", label: "Дата счёта" },
    { key: "due_date", label: "Срок оплаты" },
    { key: "period", label: "Период (Апрель 2026)" },
    { key: "tenant_name", label: "Название плательщика" },
    { key: "tenant_bin", label: "БИН/ИИН плательщика" },
    { key: "tenant_address", label: "Адрес плательщика" },
    { key: "tenant_iik", label: "ИИК плательщика" },
    { key: "tenant_bank", label: "Банк плательщика" },
    { key: "landlord_name", label: "Название поставщика" },
    { key: "landlord_bin", label: "БИН поставщика" },
    { key: "landlord_iik", label: "ИИК поставщика" },
    { key: "landlord_bik", label: "БИК поставщика" },
    { key: "landlord_bank", label: "Банк поставщика" },
    { key: "landlord_second_iik", label: "Второй ИИК поставщика" },
    { key: "landlord_second_bik", label: "Второй БИК поставщика" },
    { key: "landlord_second_bank", label: "Второй банк поставщика" },
    { key: "subtotal", label: "Сумма без НДС" },
    { key: "vat_rate", label: "Ставка НДС, %" },
    { key: "vat_amount", label: "Сумма НДС" },
    { key: "total", label: "Всего к оплате" },
    { key: "total_in_words", label: "Сумма прописью" },
    { key: "contract_number", label: "Номер договора" },
    { key: "purpose", label: "Назначение платежа" },
    { key: "items", label: "Список услуг (#each items)" },
  ],
  ACT: [
    { key: "act_number", label: "Номер акта" },
    { key: "act_date", label: "Дата акта" },
    { key: "period_start", label: "Период от" },
    { key: "period_end", label: "Период до" },
    { key: "tenant_name", label: "Заказчик — название" },
    { key: "tenant_bin", label: "Заказчик — БИН/ИИН" },
    { key: "tenant_director", label: "Заказчик — директор" },
    { key: "landlord_name", label: "Исполнитель — название" },
    { key: "landlord_bin", label: "Исполнитель — БИН" },
    { key: "landlord_director", label: "Исполнитель — директор" },
    { key: "subtotal", label: "Сумма без НДС" },
    { key: "vat_rate", label: "Ставка НДС, %" },
    { key: "vat_amount", label: "НДС" },
    { key: "total", label: "Всего" },
    { key: "total_in_words", label: "Сумма прописью" },
    { key: "contract_number", label: "Номер договора" },
    { key: "items", label: "Список услуг (#each items)" },
  ],
  RECONCILIATION: [
    { key: "period_start", label: "Начало периода" },
    { key: "period_end", label: "Конец периода" },
    { key: "tenant_name", label: "Контрагент" },
    { key: "tenant_bin", label: "БИН контрагента" },
    { key: "landlord_name", label: "Наша организация" },
    { key: "landlord_bin", label: "БИН наш" },
    { key: "total_debit", label: "Всего начислено" },
    { key: "total_credit", label: "Всего оплачено" },
    { key: "balance", label: "Сальдо" },
    { key: "balance_in_words", label: "Сальдо прописью" },
    { key: "entries", label: "Список операций (#each entries)" },
  ],
}
